language: r
sudo: required
cache: packages
warnings_are_errors: true

r:
  - release
  - devel

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

r_packages:
  - devtools
  - sessioninfo

r_github_packages:
  - rstudio/bookdown
  - r-lib/sessioninfo
  - Rdatatable/data.table
  - osofr/simcausal
  - osofr/condensier
  - tlverse/hal9001
  - tlverse/delayed
  - tlverse/origami
  - tlverse/sl3
  - tlverse/tmle3
  - tlverse/tmle3mopttx
  - tlverse/tmle3shift

before_script:
  - chmod +x ./handbook/_build.sh
  - chmod +x ./handbook/_deploy.sh

script:
  - cd handbook
  - ./_build.sh
  - test $TRAVIS_BRANCH = "master" && ./_deploy.sh
